# CI Link checker configuration
# See https://github.com/lycheeverse/lychee/blob/master/lychee.example.toml

# Exclude URLs and mail addresses from checking (supports regex).
# Please explain the inclusion of each one.
exclude = [
    # This will always be a 404 unless you're authed
    "https://github.com/satisfactorymodding/UnrealEngine/",
    # This will always be a 404 unless you're authed
    "https://github.com/EpicGames/UnrealEngine/",
    # This will always be a 404 unless you're authed
    "https://github.com/SatisfactoryModdingUE/UnrealEngine/",
    # Site seems to disallow robots
    "https://cable.ayra.ch/satisfactory/editor.php",
    # Reports a 404 despite the link working?
    "https://www.unrealengine.com/en-US/blog/download-our-new-blender-addons",
    # Possible not allowing robots, receiving 403
    "https://steamdb.info/app/526870/",
    # Don't check edit links for the docs itself (randomly 403s but also why check these anyways)
    "https://github.com/satisfactorymodding/Documentation/edit/",
    # Don't check license links at the bottom of pages, seems to frequently "Failed: Network error: unexpected EOF"
    "https://www.gnu.org/",
    # This is a valid page but still 404s for some reason
    "https://www.audiokinetic.com/en/download/",
    # unable to get local issuer certificate
    "https://questions.satisfactorygame.com/",
    # 403s despite being valid page
    "https://stackoverflow.com/questions/",
    # 403s despite being valid page
    "https://www.unrealengine.com/en-US/ue-on-github",
    # 403s despite being valid pages, we should try to get this working somehow, since these links can change without warning
    "https://docs.unrealengine.com/"
]

# Exclude these filesystem paths from getting checked.
# TODO find a better way to handle sub-mods, as they currently must be ignored here
# else they'll fail the the whole build if they have broken links.
exclude_path = [
    "./build/site/ficsit-networks/",
    "./build/site/ficsitremotemonitoring/"
]
